// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxRtVJt4-ij13wgWfQpAvo7WtRi3otdAs',
    appId: '1:201011016339:web:f8b8d4148e0ae2cc181366',
    messagingSenderId: '201011016339',
    projectId: 'layover-070499',
    authDomain: 'layover-070499.firebaseapp.com',
    storageBucket: 'layover-070499.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhQ2RnEugXW-jCuWjSK_TvAYZBkidevBI',
    appId: '1:201011016339:android:f2695961bcaab016181366',
    messagingSenderId: '201011016339',
    projectId: 'layover-070499',
    storageBucket: 'layover-070499.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUmsaicCp59mU6lMLlmyl34HgzKZDx4r4',
    appId: '1:201011016339:ios:571521af851d465a181366',
    messagingSenderId: '201011016339',
    projectId: 'layover-070499',
    storageBucket: 'layover-070499.appspot.com',
    iosClientId: '201011016339-apl63p64vl27jdp8utkgcu3gnr9pjanf.apps.googleusercontent.com',
    iosBundleId: 'com.layover.layover',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUmsaicCp59mU6lMLlmyl34HgzKZDx4r4',
    appId: '1:201011016339:ios:571521af851d465a181366',
    messagingSenderId: '201011016339',
    projectId: 'layover-070499',
    storageBucket: 'layover-070499.appspot.com',
    iosClientId: '201011016339-apl63p64vl27jdp8utkgcu3gnr9pjanf.apps.googleusercontent.com',
    iosBundleId: 'com.layover.layover',
  );
}
