# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Runner' do
 
  #use_frameworks!
  pod 'Fabric'
  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '9.4.0' 

end
